name: Node.js Package

on:
  push:
    branches: [ develop, staging ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run ci

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging' # Deploy only from Staging branch
    steps:
    - name: Deploy to Production
      run: npm run deploy
